CREATE TABLE Fall22_S004_13_SERVICE(
    SSID INT PRIMARY KEY,
    S_TYPE VARCHAR(50) NOT NULL
    );
CREATE TABLE Fall22_S004_13_PERSON(
    PID INT PRIMARY KEY,
    FNAME VARCHAR(50) NOT NULL,
    MNAME VARCHAR(50),
    LNAME VARCHAR(50) NOT NULL,
    P_ADDRESS VARCHAR(100) NOT NULL,
    GENDER VARCHAR(50),
    BDATE DATE NOT NULL
    );
CREATE TABLE Fall22_S004_13_ROOMS(
    RID INT PRIMARY KEY,
    SSID INT,
    BEDS INT NOT NULL,
    CHARGE FLOAT NOT NULL,
    FOREIGN KEY (SSID) references Fall22_S004_13_SERVICE(SSID)
    );
CREATE TABLE Fall22_S004_13_ENTERPRISE(
    REGIONID VARCHAR(10) PRIMARY KEY
);
CREATE TABLE Fall22_S004_13_HOSPITAL(
    HID INT PRIMARY KEY,
    HNAME VARCHAR(100),
    STREET VARCHAR(100),
    CITY VARCHAR(100),
    ZIP INT,
    REGIONID VARCHAR(10),
    FOREIGN KEY (REGIONID) REFERENCES Fall22_S004_13_ENTERPRISE(REGIONID),
    REGISTERED_BEDS INT
);
CREATE TABLE Fall22_S004_13_DEPARTMENT(
    DID INT PRIMARY KEY,
    D_NAME VARCHAR(50) NOT NULL,
    STARTING_DATE DATE DEFAULT NULL,
    HID INT,
    EID INT DEFAULT NULL,
    FOREIGN KEY (HID) REFERENCES Fall22_S004_13_HOSPITAL(HID)
);

CREATE TABLE Fall22_S004_13_EMPLOYEE(
    PID INT,
    FOREIGN KEY (PID) REFERENCES Fall22_S004_13_PERSON(PID),
    EID INT PRIMARY KEY,
    SALARY INT NOT NULL,
    SSN INT NOT NULL,
    EMPTYPE VARCHAR(50) NOT NULL,
    DID INT,
    FOREIGN KEY (DID) REFERENCES Fall22_S004_13_DEPARTMENT(DID),
    S_DATE DATE NOT NULL,
    E_DATE DATE DEFAULT NULL
    );

ALTER TABLE Fall22_S004_13_DEPARTMENT ADD FOREIGN KEY (EID) REFERENCES Fall22_S004_13_EMPLOYEE(EID);


CREATE TABLE Fall22_S004_13_PHARMACY_INVENTORY(
    PrID INT PRIMARY KEY,
    QUANTITY INT,
    PI_NAME VARCHAR(100),
    HID INT,
    FOREIGN KEY (HID) REFERENCES Fall22_S004_13_HOSPITAL(HID)
);

CREATE TABLE Fall22_S004_13_MEDICINES(
    SSID INT,
    FOREIGN KEY (SSID) REFERENCES Fall22_S004_13_SERVICE(SSID),
    MID INT PRIMARY KEY,
    M_NAME VARCHAR(100) NOT NULL,
    QUANTITY INT NOT NULL,
    CHARGE FLOAT NOT NULL,
    PRID INT,
    FOREIGN KEY (PRID) REFERENCES Fall22_S004_13_PHARMACY_INVENTORY(PRID)
    );
CREATE TABLE Fall22_S004_13_CONSULTANCY(
    SSID INT,
    FOREIGN KEY (SSID) REFERENCES Fall22_S004_13_SERVICE(SSID),
    CID INT PRIMARY KEY,
    CHARGE FLOAT NOT NULL,
    C_DESCRIPTION VARCHAR(100)
    );
CREATE TABLE Fall22_S004_13_PATIENT(
    PID INT,
    FOREIGN KEY (PID) REFERENCES Fall22_S004_13_PERSON(PID),
    PA_ID INT PRIMARY KEY,
    HID INT,
    FOREIGN KEY (HID) REFERENCES Fall22_S004_13_HOSPITAL(HID),
    S_DATE DATE NOT NULL,
    E_DATE DATE
    );
CREATE TABLE Fall22_S004_13_ORDERS(
    O_ID INT PRIMARY KEY,
    O_DATE DATE NOT NULL,
    O_TYPE VARCHAR(100) NOT NULL,
    O_DESCRIPTION VARCHAR(100),
    RID INT,
    FOREIGN KEY (RID) REFERENCES Fall22_S004_13_ROOMS(RID),
    MID INT,
    FOREIGN KEY (MID) REFERENCES Fall22_S004_13_MEDICINES(MID),
    CID INT,
    FOREIGN KEY (CID) REFERENCES Fall22_S004_13_CONSULTANCY(CID),
    TID INT DEFAULT NULL,
    PA_ID INT,
    FOREIGN KEY (PA_ID) REFERENCES Fall22_S004_13_PATIENT(PA_ID)
    );
CREATE TABLE Fall22_S004_13_FINANCE(
    TID INT PRIMARY KEY,
    F_TYPE VARCHAR(100) NOT NULL,
    AMOUNT FLOAT NOT NULL,
    EXP_INCOME VARCHAR(10) NOT NULL,
    O_ID INT,
    FOREIGN KEY (O_ID) REFERENCES Fall22_S004_13_ORDERS(O_ID)
    );
ALTER TABLE Fall22_S004_13_ORDERS ADD FOREIGN KEY (TID) REFERENCES Fall22_S004_13_FINANCE(TID);


CREATE TABLE Fall22_S004_13_PERSON_PHNO(
    PID INT,
    FOREIGN KEY (PID) REFERENCES Fall22_S004_13_PERSON(PID),
    PH_NO INT,
    PRIMARY KEY(PID,PH_NO)
    );
CREATE TABLE Fall22_S004_13_PATIENT_AILMENT(
    PA_ID INT ,
    AILMENT VARCHAR(50),
    PRIMARY KEY(PA_ID, AILMENT)
);
CREATE TABLE Fall22_S004_13_DEPARTMENT_LOCATION(
    DID INT,
    FOREIGN KEY (DID) REFERENCES Fall22_S004_13_DEPARTMENT(DID),
    LOCATIONS VARCHAR(50),
    PRIMARY KEY(DID,LOCATIONS)
);
CREATE TABLE Fall22_S004_13_INSURANCE(
    InID INT PRIMARY KEY,
    INS_PROVIDER VARCHAR(50)
);

CREATE TABLE Fall22_S004_13_CONTAINS(
    RID INT,
    FOREIGN KEY (RID) REFERENCES Fall22_S004_13_ROOMS(RID),
    HID INT,
    FOREIGN KEY (HID) REFERENCES Fall22_S004_13_HOSPITAL(HID),
    C_TYPE VARCHAR(50),
    NO_OF_ROOMS INT,
    PRIMARY KEY(RID,HID) 
);
CREATE TABLE Fall22_S004_13_CONSULTED_BY(
    CID INT,
    FOREIGN KEY (CID) REFERENCES Fall22_S004_13_CONSULTANCY(CID),
    EID INT,
    FOREIGN KEY (EID) REFERENCES Fall22_S004_13_EMPLOYEE(EID),
    PRIMARY KEY(CID,EID)
);
CREATE TABLE Fall22_S004_13_INSURED_BY(
    PA_ID INT,
    FOREIGN KEY (PA_ID) REFERENCES Fall22_S004_13_PATIENT(PA_ID),
    InID INT DEFAULT NULL,
    FOREIGN KEY (InID) REFERENCES Fall22_S004_13_INSURANCE(InID),
    PRIMARY KEY(PA_ID)
);
